site_name: Converge
site_description: User documentation for Converge
repo_name: Converge
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Configuration: configuration.md
  - CLI: cli.md
  - Concepts:
      - How Converge Runs: how-converge-runs.md
  - Troubleshooting: troubleshooting.md
theme:
  name: material
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.details
